Logging: 
  IncludeScopes: false
  Debug:
    LogLevel: 
      Default: Information
  Console:
    LogLevel: 
      Default: Information
      Pivotal: Debug
      Steeltoe: Debug
eureka:
  client: 
  validate_certificates: false
